# CSV files are availaible at https://github.com/nishkalrao20/nc_ringdown
[I/O]
outdir            = nc_ringdown/src/tests/HypTan_global
screen-output     = 0

[NR-data]
catalog           = RIT
ID                = 1334
l-NR              = 2
m                 = 2
error             = late-time-const-error
properties-file   = nc_ringdown/src/data/RIT_Parameters_non-spinning.csv

[Model]
template          = TEOBPM
TEOB-template     = HypTan
TEOB-global-fit	  = 1
TEOB-merger-data  = 0

[Inference]
nlive             = 128
maxmcmc           = 128
t-start           = 0
seed              = 1

[Priors]
c3A_22-min        = -4.5
c3A_22-max        = 0.9
c3p_22-min        = 0
c3p_22-max        = 10
c4p_22-min        = 0
c4p_22-max        = 10
