# CSV files are availaible at https://github.com/nishkalrao20/nc_ringdown
[I/O]
outdir            = nc_ringdown/src/tests/RatExp_global
screen-output     = 0

[NR-data]
catalog           = RIT
ID                = 1334
l-NR              = 2
m                 = 2            
error             = late-time-const-error
properties-file   = nc_ringdown/src/data/RIT_Parameters_non-spinning.csv
fits-file         = nc_ringdown/src/data/bayesian_fit_coefficients/order_fits_nu_emrg_bmrg_3.csv

[Model]
template          = TEOBPM
TEOB-template     = RatExp
TEOB-global-fit	  = 1
TEOB-merger-data  = 1

[Inference]
nlive             = 128
maxmcmc           = 128
t-start           = 0
seed              = 1

[Priors]
